import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'
import Instagram from '../components/Instagram'
import Footer from '../components/Footer'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Photography Webpage - NextJS App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero heading='Mary Janne Photography' message='Photographic coverage of events and conferences' />
            <Slider slides={SliderData} />
            <Instagram />
            <Footer />
        </div>
    )
}
